#!/bin/sh
set -e
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
    systemctl stop iureti-discovery.service || true
    systemctl disable iureti-discovery.service >/dev/null 2>&1 || true
fi
exit 0
